version: '3.6'
services:
    elasticsearch:
        container_name: ddev-${DDEV_SITENAME}-elasticsearch
        hostname: ${DDEV_SITENAME}-elasticsearch
        image: elasticsearch:7.6.1
        ports:
            - "9205"
            - "9300"
        environment:
            - cluster.name=docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - VIRTUAL_HOST=$DDEV_HOSTNAME
            - HTTP_EXPOSE=9205:9205
            - HTTPS_EXPOSE=9201:9205
        labels:
            com.ddev.site-name: ${DDEV_SITENAME}
            com.ddev.approot: $DDEV_APPROOT
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
            - ".:/mnt/ddev_config"
    web:
        links:
            - elasticsearch:elasticsearch

volumes:
    elasticsearch:
